### ISSUE TITLE
AttributeError: 'Token' object has no attribute '_collision_rect'

### ISSUE THREAD

**Issue by zormit** [asbl/miniworldmaker#12]
While playing around with example/basics/playground_basics.py:

```
Traceback (most recent call last):
  File "playground_basics.py", line 11, in <module>
    player.add_costume(source="images/player_1.png")
  File "source/miniworldmaker/tokens/token.py", line 312, in add_costume
    if self.collision_rect == "static-rect":
  File "source/miniworldmaker/tokens/token.py", line 750, in collision_rect
    return self._collision_rect
AttributeError: 'Token' object has no attribute '_collision_rect'
```

**Comment by asbl** [comment]
closed, fixed
